# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static-pv
  namespace: test-csi
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  csi:
    driver: com.mapr.csi-kdf
    volumeHandle: test-id
    volumeAttributes:
      volumePath: "/static" # Default: "/"
      cluster: demo.mapr.com
      cldbHosts: maprdemo
      securityType: "Unsecure" # Default: Unsecure
